[project]
name = "learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "graphviz>=0.21",
    "matplotlib>=3.10.0",
    "pytest>=9.0.3",
    "scikit-learn>=1.7.0",
]

[dependency-groups]
dev = [
    "torch>=2.13.0",
]
